### ISSUE TITLE
Doesn't scroll to page on selecting it in page selector if screen is small: V2

### ISSUE THREAD

**Issue by AbhishekKS** [surveyjs/survey-creator#1485]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?
Page selection is not always focused through page navigation selector.

### What is the expected behavior?
Selected page through page navigation selector should be focused.

### How would you reproduce the current behavior (if this is a bug)?
1) Open an empty designer page.
2) Add three pages, each page having one radio button question.
3) Through page navigation selector first select page 1, then select page 2 OR page 3. Page 2 OR 3 gets selected but is not focused on the screen.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

Test code

```
your_code_here

```

### Specify your

* browser: Chrome Version 91.0.4472.124
* editor version:

**Comment by andrewtelnov** [comment]
@AbhishekKS There is a bug, but is another type of bug. This example should show how to create single page survey. It should not allow to create the second page at all. I will take a look.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
@AbhishekKS I was wrong. It is the first example. Could you please explain the issue in more details? I could not reproduce it.
Probably we have already fixed it. As I told because our Azure pipeline that updates our test website automatically on every commit into master of any library failed to work for several days. We fixed it yesterday.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Hi Andrew,
I can still see a focus issue when I select pages through the page navigation selector. I have attached a video for the same. As you can see in the video when I select Page 2 and Page 3, these pages are not focused on their own, and I have to scroll down to find them out.

Thanks
Abhishek


https://user-images.githubusercontent.com/13827554/125429194-eff7a07d-548a-4b92-9dfe-bbb6b9a90aaf.mov

**Comment by andrewtelnov** [comment]
@AbhishekKS What browser do you use? I can't reproduce it using Chrome.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
I'm using Chrome browser (Version 91.0.4472.124 (Official Build) (64-bit)) on Windows 10. I don't see anything in the console either other than some legitimate warnings.

Thanks
Abhishek

![image](https://user-images.githubusercontent.com/13827554/125432170-54d535fa-5314-4058-bc9c-8bed27cc919e.png)

**Comment by andrewtelnov** [comment]
@AbhishekKS I will ask others to check.

Thank you,
Andrew

**Comment by andrewtelnov** [comment]
Could you please make sure that you don't use the cache version?

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
I just checked in the new incognito window, I can still see the focus issue.

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS FYI: We have reproduce the issue.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Hi Andrew,
Any plan when we are going to fix this? Can we expect this fix in the coming release 1.8.57?

**Comment by tsv2013** [comment]
@AbhishekKS  This task is in our task list. I hope you do understand we're working hard on Creator V2 and have limited resources.

**Comment by andrewtelnov** [comment]
@AbhishekKS I believe you are going to post more bugs here which is great. That is why I want to explain how we work here.

For released products we have zero bugs rule and we try to fix all bugs. For products in developement, we consider bugs and new functionality in the same way, having one list for them. Bugs have more priorites, but still they are in one list with features. Every item has value  (value for our customers) and cost (our developement time). We want to implement first items with the best value/cost ratio.
This bug is not a show stopper for you, it is not even easy to reproduce. We will take a look at it soon. If we can fix it fast, we will fix. If could not fix it fast, we will posponed it a little bit.
For your project, is far more important to let us create couple examples: Change themes and render custom toolbox and property pane. They are show stoppers for your project, so we better work on them first.

Thank you,
Andrew

**Comment by AbhishekKS** [comment]
Just FYI...
This seems to be working fine now if I check on your dev platform. Not sure some recent commit fixed this.

Thanks
Abhishek

**Comment by andrewtelnov** [comment]
@AbhishekKS Yes, I wanted to check it after [this fix](https://github.com/surveyjs/survey-creator/issues/1537). It actually fixed several issues and was very likely fixed this one as well.

Thank you,
Andrew

**Comment by tsv2013** [comment]
Right now I can't reproduce the issue on our test site - https://surveyjstest.azurewebsites.net//Examples/CreatorSinglePage?id=options&platform=ReactjsV2&theme=modern

**Comment by tsachinn07** [comment]
Hi @tsv2013 ,

We are seeing this issue on our desktop. When we are selecting pages first time through Page navigator or Property Selector, scrolling is not positioning properly. But after that, It works fine. Sharing the plunkr link. Please go through it.
https://plnkr.co/edit/l8pvkGcBUAXkSkN5?preview

Thanks,
Sachin

**Comment by vikkrantxx7** [comment]
So basically this is happening because of dynamic rendering.
The page is scrolled into the view correctly but since the list is long and is not rendered yet,
the questions starts to render and push the focused page down out of the view.

Page 3 selected and before question are rendered-
![image](https://user-images.githubusercontent.com/37444378/134498740-a0465cca-18be-4458-a021-9eafd23ee04c.png)

After questions are rendered-
![image](https://user-images.githubusercontent.com/37444378/134498878-916474f3-dc09-4c95-a6ec-1a5791071def.png)

**Comment by tsv2013** [comment]
Thank you for the clarifications. Yes. I see the issue now.

But it doesn't related to original issue header - "Doesn't scroll to page on selecting it in page selector if screen is small: V2". I was checking this issue by the video from this comment - https://github.com/surveyjs/survey-creator/issues/1485#issuecomment-878935306

It is related to the lazy rendering mode of the content survey.

We'll work on the fix.

**Comment by tsv2013** [comment]
surveyjstest site will be updated in 2-3 hours and you can check the fix

**Comment by vikkrantxx7** [comment]
@tsv2013 is there a way this can be smoothly scrolled?
As I make scroll-behavior: smooth. This is breaking.
```css
.svc-tab-designer.sd-root-modern {
    scroll-behavior: smooth;
}
```

https://plnkr.co/edit/wBp0ju16ATVIsWYL

**Comment by tsv2013** [comment]
>is there a way this can be smoothly scrolled?

Right now - no. And there are two points:
- Page can contain tens of questions. Thus scroll with the constant speed from 1st to last page can take quite long time
- Invisible questions are not rendered until they are not visible. In case of smooth scrolling they will be rendered and Y coordinate of destination page will be changed while scrolling

We'll see what we can do with smooth scrolling, but right now I don't see an easy way to do it.
