### ISSUE TITLE
Text overflowing and maxLength issue in designer v2

### ISSUE THREAD

**Issue by vikkrantxx7** [surveyjs/survey-creator#1585]
### Are you requesting a feature, report a bug, or ask a question?

Reporting a bug

### What is the current behavior?

Text overflowing and maxLength override

### What is the expected behavior?

The text should not overflow and maxLength should be applied while changing directly through the designer view

### How would you reproduce the current behavior (if this is a bug)?

Just keep typing long text

#### Provide the test code and the tested page URL (if applicable)

Tested page URL: https://surveyjstest.azurewebsites.net/Examples/Survey-Creator?id=addproperties&platform=ReactjsV2&theme=bootstrap#content-result

Test code

```
Not required

```

### Specify your

* browser: chrome 92
* editor version: 1.8.58

![image](https://user-images.githubusercontent.com/37444378/127969527-154b0e08-2c36-4065-9a18-b8128e32cfb4.png)

**Comment by AbhishekKS** [comment]
I see the CSS changes made against this ticket for questions title reflecting on your dev website. But I still see the overflowing issue. I guess the issue of overflowing was reported overall for all string text editors on the designer page. It's not working for Question Title, Question Desc, options text, etc. I'm seeing this on Chrome 92.0.4515.131. Could you please check?

**For Page Title, Page Desc, Question Title, Question Desc**

![image](https://user-images.githubusercontent.com/13827554/128200201-b1d2eda6-abf5-4a47-89dc-7b93926b1a6b.png)

**For Options text (Here Radio Group question):**

![image](https://user-images.githubusercontent.com/13827554/128200350-6e4f0e47-d527-4c2a-aa5a-f6c530062610.png)

**Comment by tsv2013** [comment]
I've added style that should fix it

**Comment by AbhishekKS** [comment]
Hi @tsv2013,
This fixed the overlapping for the Question title. But the issue still remains for Question Desc, Page Title, Page Desc, Options text, and maybe at other places where we input text on the designer page. I highlighted that in the comment above.

![image](https://user-images.githubusercontent.com/13827554/128221995-253c5644-ff16-4042-8fc6-26656af30e49.png)

Thanks
Abhishek

**Comment by tsv2013** [comment]
Thank you for the update. We'll take a look

**Comment by tsv2013** [comment]
@AbhishekKS  I've fixed titles. If you find something, write us.

**Comment by vikkrantxx7** [comment]
@tsv2013 the overflow is fixed but defining the maxlength has no impact while the text is entered through the designer view.
``Survey.Serializer.findProperty('survey', 'title').maxLength = 4``

https://user-images.githubusercontent.com/37444378/128663875-24ae30bc-ed7d-4b1a-bc21-0d0257a440ba.mp4

**Comment by tsv2013** [comment]
@vikkrantxx7 I've created a separate issue - https://github.com/surveyjs/survey-creator/issues/1608
